### ISSUE TITLE
Pydantic Performance drag

### ISSUE THREAD

**Issue by jeremyfx** [tellor-io/telliot-core#106]
While Pydantic is awesome for the specific use case of parsing and coercing incoming api data where the structure is not guaranteed to be consistent, it does come with a significant performance hit. If the codebase is ever refactored and the specific use case I mentioned is not a necessity, I would suggest using dataclasses instead.
![21-10-2021-10-27-01](https://user-images.githubusercontent.com/85967359/138298365-e68ed5d7-46fd-4a90-bd58-635735cd0326.png)

**Comment by clamdad** [comment]
See #128 for follow-up
