### ISSUE TITLE
-p function not working across short time frames

### ISSUE THREAD

**Issue by LP-Crypto-Scholar** [tellor-io/telliot-core#164]
Another reporter submitted a report 1 block ahead of me, they got the reward which in turn should have reset the profitability equation back to -99.99% in the next block. I had my reporter operating with the function 'telliot-examples -lid 1 report -p -30'. The -p -30 function should have automatically stopped my report from submitting on the next block however it did not. 

Winning report:
https://etherscan.io/tx/0x88cfde4709bd69932a015d31b21171da87b683aca7819049d193a336a9caceaf
My report:
https://etherscan.io/tx/0x4f7b1668ffc0d6e701bf0032c70192526e160b88dcb2c176d44d6e7a4913971c

**Comment by clamdad** [comment]
Also related to https://github.com/tellor-io/tellorX/issues/133

**Comment by oraclown** [comment]
@tallywiesenberg I think this could have happened because of the retries. It doesn't check for profitability between retries.. Maybe we take out retries?
