### ISSUE TITLE
Auto update log when -mgp isnt satisfied

### ISSUE THREAD

**Issue by Crypto-Paganism** [tellor-io/telliot-core#169]
Currently the logs refresh's every few seconds when the following command is entered:
telliot-examples -lid 1 report -p 20 

Whereas when you place -mgp in the command, the log does not refresh. Not sure if telliot is running or if the command has stalled telliot. Using the following command:
telliot-examples -lid 1 report -p 20 -mgp 70

**Comment by tallywiesenberg** [comment]
@Crypto-Paganism please move this issue to `telliot-feed-examples` because `telliot-examples` relates to that repo!
