### ISSUE TITLE
Enable reporters to submit using maxFee and maxPriorityFee

### ISSUE THREAD

**Issue by Crypto-Paganism** [tellor-io/telliot-core#180]
Add commands to enable custom Max Fee and Max Priority Fee inputs for when reports submit rather than relying on safeLow, Average, Fast and Fastest. This will help combat frontrunners until the front running issue is solved.

**Comment by clamdad** [comment]
I believe this will be covered by #166

**Comment by oraclown** [comment]
This is available using the following flags of `telliot-feed-examples` CLI: `-tx/--tx-type`, `-mf/--max-fee`, and `-pf/--priority-fee`. Example:
```
telliot-examples -st staker1 -sgt sig1 -fb report -tx 2 -mf 120 -pf 10 -p 10
```
