### ISSUE TITLE
Change staker list to accounts list?

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-core#189]
We might want to consider changing stakes list to a more broad name like "Account List", because it now holds things like staked addresses and signatory accounts for the Flashbots relay. Related to [#78](https://github.com/tellor-io/telliot-feed-examples/issues/78), because if we're iterating through the StakerList, we won't be able to tell which kind of account is a staker vs signatory account.

**Comment by clamdad** [comment]
With you on this.  Maybe more general account "private keys" sort of thing.  Each can still have a user-provided tag.  Then stakers.yaml can simply be a list of account tags.   I also am wondering is we should provide some sort of password access to protect them on a local machine.  I'd have to think there is something out there already like this.

**Comment by oraclown** [comment]
> With you on this. Maybe more general account "private keys" sort of thing. Each can still have a user-provided tag. Then stakers.yaml can simply be a list of account tags. I also am wondering is we should provide some sort of password access to protect them on a local machine. I'd have to think there is something out there already like this.

Password access to what? The yaml file that's holding all the account info (private keys, tags, account hex, etc.)?

**Comment by clamdad** [comment]
I'm thinking of something [like this](https://github.com/ethereum/eth-keyfile) and require the user to input a password to unlock, something [like here](https://github.com/ethereum/eth-keyfile).  Of course an inconvenience to type password each time, but more secure.
