### ISSUE TITLE
Update reporter sync schedule

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-core#255]
Why are we reporting legacy query IDs still? For specific users? I think some of those query IDs are hard-coded in Liquity contracts. Regardless, we should also:
- [ ] add the spot price equivalent of those queries to `reporter_sync_schedule`
```python
reporter_sync_schedule: List[str] = [
    "eth-usd-legacy",
    "btc-usd-legacy",
    "trb-usd-legacy",
    "ohm-eth-spot",
]
```
- [ ] update `reporter_sync_schedule` to include all current query IDs, as there's a few missing
- [ ] make `reporter_sync_schedule` automatically update when new query IDs are added

**Comment by akremstudy** [comment]
hey @oraclown, what do you think about doing it this way? so it can always be updated automatically and a full list.
```python
reporter_sync_schedule: List[str] = []
with open("scripts/query_catalog.yaml", 'r') as tags:
    catalog = yaml.safe_load(tags)
    for i in catalog:
        reporter_sync_schedule.append(i['tag'])
```
if you print(reporter_sync_schedule),
output is: ```['eth-usd-legacy', 'btc-usd-legacy', 'ampl-legacy', 'uspce-legacy', 'trb-usd-legacy', 'eth-jpy-legacy', 'ohm-eth-spot', 'vsq-usd-spot', 'bct-usd-spot', 'dai-usd-spot', 'ric-usd-spot', 'idle-usd-spot', 'mkr-usd-spot', 'sushi-usd-spot', 'matic-usd-spot', 'usdc-usd-spot']```

**Comment by oraclown** [comment]
> hey @oraclown, what do you think about doing it this way? so it can always be updated automatically and a full list.
> 
> ```python
> reporter_sync_schedule: List[str] = []
> with open("scripts/query_catalog.yaml", 'r') as tags:
>     catalog = yaml.safe_load(tags)
>     for i in catalog:
>         reporter_sync_schedule.append(i['tag'])
> ```
> 
> if you print(reporter_sync_schedule), output is: `['eth-usd-legacy', 'btc-usd-legacy', 'ampl-legacy', 'uspce-legacy', 'trb-usd-legacy', 'eth-jpy-legacy', 'ohm-eth-spot', 'vsq-usd-spot', 'bct-usd-spot', 'dai-usd-spot', 'ric-usd-spot', 'idle-usd-spot', 'mkr-usd-spot', 'sushi-usd-spot', 'matic-usd-spot', 'usdc-usd-spot']`

Great idea! That works. And maybe iterate through `query_catalog` from `telliot_core.data.query_catalog` instead of having to read in the yaml file.
