### ISSUE TITLE
Create new config flag for different submit address

### ISSUE THREAD

**Issue by themandalore** [tellor-io/telliot-core#307]
Allow the user to configure telliot to submit to a different address
e.g - https://github.com/tellor-io/sampleReporterFailContract. 

caveat - when checking if the user is staked, you need to check
You can still do depositStake/all functions to new address though

**Comment by oraclown** [comment]
Related: [#259](https://github.com/tellor-io/telliot-feeds/issues/259)

**Comment by oraclown** [comment]
(from dev call): `telliot` probably makes contract reads back to the main flex contract, but any writes through the proxy

**Comment by oraclown** [comment]
This functionality is available
