### ISSUE TITLE
Telliot Reporter are incorrect

### ISSUE THREAD

**Issue by LP-Crypto-Scholar** [tellor-io/telliot-core#332]
⚡🤖⚡ Reporting through Flashbots relay ⚡🤖⚡
Signature account: 0xE6488539F46f9e1E84A7B811c5bc405D00fB0382
Reporting with synchronized queries
Current chain ID: 1
Expected percent profit: 10.0%
Transaction type: 2
Gas Limit: 500000
Legacy gas price (gwei): None
Max fee (gwei): 10
Priority fee (gwei): 3
Gas price speed: fast

Press [ENTER] to confirm settings.

❗Telliot will automatically stake more TRB if your stake is below or falls below the stake amount required to report.
If you would like to stake more than required enter the TOTAL stake amount you wish to be staked.

Enter amount TRB to stake if unstaked [10.0]:
INFO    | telliot_feeds.reporters.tellorflex | Reporting with account: 0xBe3FC39CBAA1Ed9bfcdF1E284f101DE77ea5203A
INFO    | telliot_feeds.reporters.tellor_360 | Reporting with account: 0xBe3FC39CBAA1Ed9bfcdF1E284f101DE77ea5203A
INFO    | telliot_feeds.reporters.tellor_360 | Current Oracle stakeAmount: 100.0
INFO    | telliot_feeds.reporters.tellor_360 |
            STAKER INFO
            start date: 1667477771
            stake_balance: 3000.0
            locked_balance: 0
            last report: 0
            reports count: 0

INFO    | telliot_feeds.reporters.tips.listener.funded_feeds | No funded feeds returned by autopay function call
INFO    | telliot_feeds.reporters.tips.listener.one_time_tips | No one time tip funded queries available
INFO    | telliot_feeds.reporters.tips.suggest_datafeed | No tips available in autopay
INFO    | telliot_feeds.reporters.interval | Current query: {"type":"SpotPrice","asset":"eur","currency":"usd"}
ERROR   | telliot_feeds.sources.price.spot.bittrex | Unable to decode Bittrex JSON
INFO    | telliot_feeds.sources.price_aggregator | Running median on [0.944232, 0.9392, 0.9388, 0.94097, 0.94]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 0.94 reported at time 2022-11-03 12:27:05.571804+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of Sources used for this report are: 5
INFO    | telliot_feeds.sources.price_aggregator | Running median on [15.92, 15.91]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 15.915 reported at time 2022-11-03 12:27:05.571947+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of Sources used for this report are: 2
INFO    | telliot_feeds.reporters.tellorflex |
                tips: 13350.460800666666 TRB
                gas limit: 500000
                legacy gas price: 66

INFO    | telliot_feeds.reporters.tellorflex | Estimated profit: $212472.55
INFO    | telliot_feeds.reporters.tellorflex | tip price: 212472.58, gas costs: 0.03102
INFO    | telliot_feeds.reporters.tellorflex | Estimated percent profit: 684953425.6%
INFO    | telliot_feeds.sources.price_aggregator | Running median on [0.97528, 0.985555]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 0.9804174999999999 reported at time 2022-11-03 12:27:07.671615+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of Sources used for this report are: 2
DEBUG   | telliot_feeds.reporters.interval | Sending submitValue transaction
INFO    | telliot_feeds.reporters.interval | View reported data:
https://etherscan.io/tx/0x37cfe0947ba37a9a8e062a46b3d71c2e840edcb128756e334728c40b926c563b
^Z
[6]+  Stopped                 telliot-feeds -a eth16 -sa fbs report --flex-360 -tx 2 -pwd password -spwd password -mf 10 -pf 3 -p 10 -gl 500000

**Comment by LP-Crypto-Scholar** [comment]
Also note that the -mf integer was not respected. ie 66 gwei was used when it should have been max 10

**Comment by oraclown** [comment]
Verified this is not longer an issue
