### ISSUE TITLE
Add the option to use EIP 1559 Transactions (for Filecoin)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-core#367]
We recently deployed on Filecoin's "Hyperspace" testnet. This network is rejecting transactions created by Telliot because it does not support Legacy gas, so we will need to be able to use the new EIP 1559 standard in Telliot.

Question: Does it make sense to use EIP 1559 transactions on all networks? Could there be any gas savings for reporting?

**Comment by akremstudy** [comment]
right now its optional and I think its good that way.  we can just force EIP1559 for reporting on Filecoin network. or make EIP1559 the default. I don't think there are gas savings but I could be wrong. these are first thoughts and subject to change lol

**Comment by oraclown** [comment]
I vote just making tx type 2 (EIP 1559) the default
