### ISSUE TITLE
tellor query id

### ISSUE THREAD

**Issue by ras9481** [tellor-io/telliot-core#390]
const queryId = web3.utils.keccak256(
  web3.eth.abi.encodeParameters(
    ["string", "string", "string"],
    ["SpotPrice", "usdt", "usd"]
  )
);

This code uses the keccak256 function from the web3 library to hash the encoded parameters of the SpotPrice query. The parameters are encoded using the Ethereum ABI encoding format.
The resulting queryId will be a unique identifier for this specific SpotPrice query with the given asset and currency.

**Comment by themandalore** [comment]
Hey @ras9481 , you looking to get a USDT/USD feed up or is there another issue?

**Comment by 0xSpuddy** [comment]
@ras9481 closing these issues because I don't think they are related to issues with the telliot-core code.
