### ISSUE TITLE
update README w/ installation instructions for devs/non-devs

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-core#40]
I'm thinking a bash script (setup.sh) that our community manager (Spuddy) can copy and run the command for. Then the only other things to change will be the rpc endpoint and private key in `~/.telliot/config.yml`

**Comment by oraclown** [comment]
How to set up a development environment for new contributors, how to use & common practices with tox/mypy/etc.

**Comment by clamdad** [comment]
It would be nice to keep it cross platform using standard Python distribution.

Maybe target something like

For beginners, install from pypi:
```
pip install telliot
```
For devs, 
```
git clone https://github.com/tellor-io/pytelliot
<insert commands to create and activate VENV using requirements.txt>
pip install -e .
```

**Comment by clamdad** [comment]
Completed
